import type { CV } from './types'

// Sources: docs/JaviCebrianCV.pdf decides WHAT is shown and its order, plus the
// short blurbs, titles and dates. docs/Profile (1).pdf supplies the long text
// (`about`, role `details`, `earlierExperience`). Postal address deliberately left out.
export const cv: CV = {
  name: 'Javi Cebrián',
  tagline: 'just another geek',
  headline: 'Product Engineer building AI-native products — from 0→1 to scale.',
  location: 'London, UK',
  about: [
    'I’m a Product Engineer with 20+ years of experience building digital products, combining deep engineering expertise with product thinking, UX, and a strong focus on shipping.',
    'Currently, I work with Google DeepMind, building AI-powered products and experiences including AlphaFold Server and Weather Lab. My work sits at the intersection of engineering, product, design, and AI — turning complex technologies and scientific capabilities into intuitive, scalable products used by people around the world.',
    'My background spans the full product lifecycle, from early-stage ideas and rapid prototyping through architecture, development, launch, and iteration at scale. While I have deep expertise in frontend and user-facing engineering, I approach problems as a product engineer: choosing the right technologies and abstractions around the problem rather than limiting myself to a particular framework or layer of the stack.',
    'Over the past two decades, I’ve built products across web, mobile, SaaS, telecommunications, marketing, and video streaming. I’ve worked as an engineer and technical lead, built and led engineering teams, and founded and scaled technology companies.',
    'I’m particularly interested in AI-native products, 0→1 product development, human–AI interaction, and building new experiences around frontier technology.',
  ],
  links: [
    { label: 'LinkedIn', href: 'https://www.linkedin.com/in/javicebrian' },
    { label: 'Email', href: 'mailto:javier@aureumdigital.com' },
  ],

  experience: [
    {
      company: 'Google',
      logo: 'google.png',
      title: 'Lead Product Engineer',
      start: 'Nov 2023',
      location: 'London',
      summary:
        'Leading frontend engineering across AlphaFold Server and Weather Lab, contributing across the stack to architecture, technical decisions and production.',
      details: [
        'Product Engineer on Google DeepMind’s AlphaFold Server and Weather Lab, building AI-powered products that turn cutting-edge research into intuitive, production-grade experiences.',
        'I lead frontend engineering across both products while contributing across the stack to architecture, technical decisions and implementation. My work combines hands-on engineering, technical leadership and product thinking, with a strong focus on making complex AI and scientific capabilities accessible through high-quality user experiences.',
        {
          title: 'AlphaFold Server',
          items: [
            'Lead frontend engineering and help shape the architecture and user experience of AlphaFold Server.',
            'Own key technical decisions and implementation across complex, user-facing scientific workflows.',
            'Contribute across the stack, from API integration and architecture to production delivery.',
          ],
        },
        {
          title: 'Weather Lab',
          items: [
            'Lead frontend engineering for interactive experiences built around Google DeepMind’s AI weather models.',
            'Drive the architecture and implementation of data-intensive interfaces for exploring complex forecasts and model outputs.',
            'Contribute across the stack to turn scientific data and research capabilities into scalable, accessible product experiences.',
          ],
        },
        'Across both products, I work from product definition and architecture through hands-on implementation, launch and iteration.',
      ],
      tags: ['Angular', 'TypeScript', 'APIs', 'GCP', 'Firebase', 'Monorepo', 'Material Design'],
    },
    {
      company: 'L’Oréal / La Roche-Posay',
      logo: 'loreal.png',
      title: 'Lead Engineer',
      start: 'Jul 2023',
      end: 'Oct 2023',
      location: 'London',
      summary: 'Led engineering on a 0→1 consumer skincare prototype, working across product, UX and the full stack.',
      details: [
        'Led engineering on a 0→1 product prototype for L’Oréal, exploring and validating concepts for a new consumer skincare experience.',
        'Worked closely with product and design to rapidly turn ideas into a functional product, iterating on user experience, technical feasibility and product requirements.',
        'Worked across the stack, from the React/Next.js experience through GraphQL, Node.js, Firebase and GCP.',
      ],
      tags: ['React', 'Next.js', 'TypeScript', 'GraphQL', 'Node.js', 'Firebase', 'GCP'],
    },
    {
      company: 'Virgin Media',
      logo: 'virginmedia.png',
      title: 'Lead Frontend Engineer',
      start: 'Jul 2022',
      end: 'Jun 2023',
      location: 'London',
      summary: 'Led frontend architecture and delivery for a new customer retention product and complex upgrade journeys.',
      details: [
        'Led frontend engineering for a new customer retention product at Virgin Media, designed to improve contract upgrade journeys and reduce retention costs.',
        'Drove frontend architecture and implementation, working across complex customer journeys and integrations within a large-scale production environment.',
        'Worked closely with product, UX and backend teams from product requirements through implementation and delivery, with a strong focus on maintainability, performance and user experience.',
      ],
      tags: ['Angular', 'TypeScript', 'Nx', 'GraphQL', 'NGXS', 'Strapi', 'Monorepo'],
    },
    {
      company: 'Candy Digital',
      logo: 'candy.png',
      title: 'Frontend Engineer',
      start: 'Oct 2021',
      end: 'Jul 2022',
      location: 'New York (remote)',
      summary: 'Built consumer digital collectible products for major sports and entertainment brands including MLB and Netflix.',
      details: [
        'Built consumer-facing digital collectible products and experiences for major sports and entertainment brands, including MLB and Netflix.',
        'Worked within a fast-paced product engineering environment, building and shipping high-quality web experiences while collaborating closely with product, design and backend teams.',
        'Contributed to frontend architecture, complex product flows and GraphQL integrations, with a strong focus on performance, scalability and user experience.',
      ],
      tags: ['React', 'Next.js', 'TypeScript', 'GraphQL', 'Redux', 'Tailwind', 'AWS'],
    },
    {
      company: 'YLD',
      logo: 'yld.png',
      title: 'Lead Frontend Engineer',
      start: 'Mar 2021',
      end: 'Sep 2021',
      location: 'London',
      summary: 'Led frontend engineering for a greenfield WTA online video platform, integrating video, content and backend services.',
      details: [
        'Led frontend engineering for a greenfield online video platform for the WTA, working with Press Association to build the product from the ground up.',
        'Drove frontend architecture and implementation, integrating video, content and backend services into a scalable user-facing platform.',
        'Worked closely with product, UX and backend teams throughout architecture, development and delivery.',
      ],
      tags: ['Angular', 'TypeScript', 'Node.js', 'Express', 'NgRx', 'REST APIs'],
    },
    {
      company: 'ABOUT YOU',
      logo: 'aboutyou.png',
      title: 'Frontend Engineer',
      start: 'Nov 2020',
      end: 'Feb 2021',
      location: 'London',
      summary: 'Built and evolved customer-facing experiences across ABOUT YOU’s large-scale multi-brand e-commerce platform.',
      details: [
        'Worked on ABOUT YOU’s core e-commerce platform, building and evolving customer-facing experiences used across the company’s different brands and markets.',
        'Contributed to the architecture and development of a large-scale e-commerce platform, working across frontend and backend services in a fast-moving product environment.',
        'Collaborated with product, UX and engineering teams to deliver scalable, reusable features across multiple storefronts.',
      ],
      tags: ['Angular', 'TypeScript', 'Node.js', 'NestJS', 'NgRx', 'REST APIs'],
    },
    {
      company: 'ustwo',
      logo: 'ustwo.png',
      title: 'Frontend Engineer',
      start: 'Jun 2020',
      end: 'Oct 2020',
      location: 'London',
      summary: 'Built a new digital fertility product for Quirónsalud, contributing across frontend, backend services and integrations.',
      details: [
        'Built a new digital fertility product for Quirónsalud, creating personalised experiences to support patients throughout their treatment journey.',
        'Worked across the product stack, building the customer-facing experience and contributing to backend services, content management and platform integrations.',
        'Collaborated within a multidisciplinary product team to turn complex healthcare workflows into intuitive, accessible digital experiences.',
      ],
      tags: ['React', 'TypeScript', 'Node.js', 'MongoDB', 'Contentful', 'Auth0', 'AWS'],
    },
    {
      company: 'Kingfisher',
      logo: 'kingfisher.png',
      title: 'Lead Frontend Engineer',
      start: 'May 2019',
      end: 'Jun 2020',
      location: 'London',
      summary: 'Led frontend engineering for digital kitchen and bathroom design products across multiple European brands.',
      details: [
        'Led frontend engineering within Kingfisher’s Kitchens, Bathrooms & Spaces team, building digital products across multiple European brands and markets.',
        'Helped drive a large-scale digital transformation, bringing previously third-party capabilities and APIs in-house while evolving the architecture of customer-facing products.',
        'Led developers and worked closely with senior stakeholders, product and UX teams to improve customer journeys and build interactive tools that enabled customers to design their kitchens and bathrooms while providing stores with actionable metrics.',
      ],
      tags: ['React', 'TypeScript', 'Node.js', 'MongoDB', 'Redux', 'REST APIs', 'SSR'],
    },
    {
      company: 'Deutsche Bank',
      logo: 'deutschebank.svg',
      title: 'Frontend Engineer',
      start: 'Oct 2018',
      end: 'Apr 2019',
      location: 'London',
      summary: 'Built a data-intensive alert and surveillance platform focused on efficient investigation workflows and UX.',
      details: [
        'Built an alert and surveillance management platform for Deutsche Bank, designed to help users identify and investigate potential alerts more efficiently.',
        'Focused on simplifying complex, data-intensive workflows through high-performance user interfaces and a strong emphasis on usability and user experience.',
        'Worked within a large-scale enterprise engineering environment, integrating the frontend with backend services and contributing to the architecture and delivery of the application.',
      ],
      tags: ['Angular', 'TypeScript', 'NgRx', 'REST APIs', 'Webpack', 'WireMock'],
    },
    {
      company: 'Extreamr',
      logo: 'extreamr.png',
      title: 'Co-founder & Technical Head',
      start: 'Sep 2012',
      end: 'Jan 2020',
      location: 'Madrid',
      summary: 'Co-founded a cloud video company, leading product architecture and hands-on full-stack engineering through acquisition.',
      details: [
        'Co-founded Extreamr, a cloud video and webcasting technology company, leading the technical direction and product development from its early stages through to the company’s acquisition.',
        'Combined hands-on full-stack engineering with product architecture and technical leadership, driving the evolution and redesign of the company’s flagship webcasting platform.',
        'Worked across the entire technology stack — from user-facing applications and backend services to real-time video delivery and cloud infrastructure — while shaping product and technology strategy as the company grew.',
        'Remained deeply hands-on throughout the journey, leading architecture and engineering with a focus on scalability, performance and reliable live video experiences.',
      ],
      tags: ['Angular', 'TypeScript', 'AWS', 'HLS', 'CDN', 'Video.js', 'Wowza'],
    },
  ],

  earlierExperience: [
    {
      company: 'The BIO Agency',
      title: 'Frontend Engineer',
      start: 'Jan 2018',
      end: 'Oct 2018',
      summary: 'Transformed Arrow’s B2B platform into a modern, scalable e-commerce experience.',
      tags: ['Angular', 'TypeScript', 'RxJS', 'NgRx'],
    },
    {
      company: 'Stratagem Technologies',
      title: 'Lead Frontend Engineer',
      start: 'Jul 2017',
      end: 'Dec 2017',
      summary: 'Real-time sports trading platform built on live market streams and predictive models.',
      tags: ['Angular', 'RxJS', 'D3.js', 'WebSockets'],
    },
    {
      company: 'Gospel Technology',
      title: 'Lead Frontend Engineer',
      start: 'Jan 2017',
      end: 'Jun 2017',
      summary: 'Enterprise data platform built around blockchain and distributed ledger technology.',
      tags: ['Angular', 'D3.js', 'Hyperledger', 'AWS'],
    },
    {
      company: 'Aimia',
      title: 'Lead Frontend Engineer & Scrum Master',
      start: 'Jan 2015',
      end: 'Dec 2016',
      summary: 'Retail optimisation and prescriptive analytics products.',
      tags: ['Angular', 'Node.js', 'D3.js', 'Highcharts'],
    },
    {
      company: 'Amplefuture',
      title: 'Frontend / Video Streaming Engineer',
      start: 'Aug 2012',
      end: 'Dec 2014',
      summary: 'Real-time video conferencing, chat and video content management products.',
      tags: ['WebRTC', 'HLS', 'Wowza', 'Red5'],
    },
    {
      company: 'Stream UK',
      title: 'UI Developer',
      start: 'Nov 2010',
      end: 'Jun 2012',
      summary: 'User-facing applications for online video and streaming products.',
      tags: ['JavaScript', 'Streaming Media'],
    },
    {
      company: 'FundeSalud',
      title: 'UI Developer',
      start: 'Dec 2006',
      end: 'Mar 2009',
      location: 'Mérida',
      summary: 'Where it started: an innovative environment to experiment across the stack.',
    },
  ],

  technologies: [
    { name: 'TypeScript / JavaScript', level: 8 },
    { name: 'React / Next.js', level: 7 },
    { name: 'Angular', level: 8 },
    { name: 'Node.js', level: 7 },
    { name: 'MCP', level: 6 },
    { name: 'LLM APIs / Tools', level: 5 },
    { name: 'AI Coding / Agents', level: 7 },
    { name: 'AI SDKs / Agents', level: 5 },
    { name: 'GraphQL / REST APIs', level: 6 },
    { name: 'GCP / AWS', level: 7 },
    { name: 'RxJS / Reactive Systems', level: 7 },
    { name: 'Real-Time / WebSockets', level: 7 },
    { name: 'WebRTC / Streaming', level: 5 },
  ],
  knowledge: [
    'Product Engineering',
    'User Experience',
    'Technical Leadership',
    'Software Architecture',
    'Mockups & Prototyping',
    'AI Product Engineering',
    '0→1 Product',
  ],

  education: [
    {
      school: 'Universidad de Extremadura, Spain',
      degree: 'Computer Science',
      start: 'Sep 2006',
      end: 'Sep 2010',
      note: 'Degree not completed',
    },
  ],

  languages: [
    { name: 'Spanish', label: 'Native', proficiency: 1 },
    { name: 'English', label: 'Proficient', proficiency: 0.75 },
  ],

  achievements: [
    { title: 'Mount Kilimanjaro summit', date: '13 September 2016', detail: '19,341 ft', image: 'kilimanjaro.png' },
    { title: 'Vätternrundan', date: '16 June 2017', detail: '300 km in 12h37m', image: 'vatternrundan.png' },
  ],

  interests: [
    { name: 'Skydiving instructor', icon: 'parachute' },
    { name: 'Private pilot', icon: 'plane' },
    { name: 'Tech diver', icon: 'diver' },
    { name: 'Cycling', icon: 'bike' },
    { name: '3D printing', icon: 'printer3d' },
    { name: 'Tinkering', icon: 'wrench' },
  ],

  contact: {
    email: 'javier@aureumdigital.com',
    cta: 'Building something ambitious? Let’s talk.',
  },
}
